openapi: 3.0.0
info:
  title: Customers
  description: 
    This application allows you to create and consult information about a customer.
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: customers
    description: Everything about your customers.
paths:
  /customer:
    post:
      tags:
        - customers
      summary: Allows you to create a customer.
      operationId: createCustomer
      description: Allows you to create a customer.
      requestBody:
        required: true
        description: Allows to register a customer.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerCreate'
      responses:
        '201':
          description: The client was registered successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerConsult'
        '400':
          description: Request rejected
  /customer/{customerDocument}:
    get:
      tags:
        - customers
      summary: Allows you tu consult information about a customer.
      operationId: getCustomer
      description: Allows you to consult information about a customer.
      parameters:
        - name: customerDocument
          in: path
          description: Customer Document
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The consult of the information was made correctly.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerConsult'
        '400':
          description: The request was rejected.
        '404':
          description: The client was not found.
                
    patch:
      tags:
        - customers
      summary: Allows you to update information about the customer.
      operationId: updateCustomer
      description: Allows you to update information about the customer.
      parameters:
        - name: customerDocument
          in: path
          description: Customer Document
          required: true
          schema:
            type: string
      requestBody:
        required: true
        description: Allows you to update information about the customer.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdate'
      responses:
        '200':
          description: The information of the customer was changed successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerConsult'
        '400':
          description: Request Rejected
        '404':
          description: The customer was not found.
                
    delete:
      tags:
        - customers
      summary: Allows you to unsubscribe a customer.
      operationId: unsubscribeCustomer
      description: Allows you tu unsubscribe a customer.
      parameters:
        - name: customerDocument
          in: path
          description: Customer Document
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The customer was unsuscribe successfully.
          content:
            application/json:
              schema:
                type: string
        '400':
          description: Request Rejected.
        '404':
          description: The customer was not found.
    
  
components:
  schemas:
    CustomerCreate:
      required:
        - customerDocument
        - customerType
        - customerName
        - customerEmail
      type: object
      properties:
        customerDocument:
          type: string
        customerType:
          type: string
          enum:
            - PERSONAL
            - COMPANY
        customerName:
          type: string
        customerEmail:
          type: string
    CustomerConsult:
      type: object
      properties:
        message:
          type: string
    CustomerUpdate:
      type: object
      properties:
        customerName:
          type: string
        customerEmail:
          type: string
        
          
        
            